# Generated by Django 5.2.17 on 2026-09-28 21:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DublinAdminArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('city_center', 'City Center'), ('cultural_quarter', 'Cultural Quarter'), ('residential', 'Residential'), ('business', 'Business District'), ('recreational', 'Recreational')], max_length=50)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dublin Admin Areas',
            },
        ),
        migrations.CreateModel(
            name='DublinPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_name', models.CharField(max_length=100)),
                ('poi_type', models.CharField(choices=[('landmark', 'Landmark'), ('amenity', 'Amenity'), ('transport', 'Transport Hub'), ('attraction', 'Tourist Attraction'), ('entertainment', 'Entertainment'), ('commercial', 'Commercial'), ('education', 'Education'), ('historic', 'Historic Site')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('visitors_per_day', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dublin POI',
                'verbose_name_plural': 'Dublin POIs',
            },
        ),
        migrations.CreateModel(
            name='DublinRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=100)),
                ('road_type', models.CharField(choices=[('motorway', 'Motorway'), ('main_street', 'Main Street'), ('secondary', 'Secondary Road'), ('tertiary', 'Tertiary Road'), ('pedestrian', 'Pedestrian Street'), ('residential', 'Residential Street')], max_length=20)),
                ('speed_limit', models.IntegerField()),
                ('length_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dublin Roads',
            },
        ),
        migrations.CreateModel(
            name='LandUseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('recreational', 'Recreational'), ('mixed_use', 'Mixed Use'), ('protected', 'Protected Area')], max_length=20)),
                ('zoning_code', models.CharField(max_length=20, unique=True)),
                ('permitted_uses', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Use Zone',
                'verbose_name_plural': 'Land Use Zones',
            },
        ),
    ]
