# Generated by Django 6.1.1 on 2026-09-29 12:20

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('population', models.PositiveIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='City center coordinates', srid=4326)),
                ('elevation_m', models.IntegerField(blank=True, help_text='Elevation above sea level in meters', null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-4000), django.core.validators.MaxValueValidator(2025)])),
                ('is_capital', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-population', 'name'],
                'indexes': [models.Index(fields=['country', 'population'], name='cities_api__country_7ddc0c_idx'), models.Index(fields=['is_capital'], name='cities_api__is_capi_e3d8a0_idx'), models.Index(fields=['population'], name='cities_api__populat_68da63_idx')],
            },
        ),
    ]
